---
name: Release published

on:
  release:
    types: [ published, edited ]

permissions:
  actions: write
  checks: write
  contents: read
  deployments: read
  issues: write
  discussions: write
  packages: read
  pages: write
  pull-requests: write
  security-events: write
  statuses: write

jobs:
  add-changelog:
    name: Add Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Add Changelog
        uses: nexmo/github-actions/nexmo-changelog@main
        env:
          CHANGELOG_AUTH_TOKEN: ${{ secrets.CHANGELOG_AUTH_TOKEN }}
          CHANGELOG_CATEGORY: Server SDK
          CHANGELOG_RELEASE_TITLE: vonage-php-sdk-core
          CHANGELOG_SUBCATEGORY: php
